version: '3.8'

services:
  leads-console-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: leads-console-prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    networks:
      - leads-console-prod-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  leads-console-prod-network:
    driver: bridge
    name: leads-console-prod-network